artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/CalebEmelike/OffensiveLanguage/raw/main/nlp_processed_train.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_ingestion/nlp_processed_train.csv
  output_dir: artifacts/model_trainer/model

model_predict:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_ingestion/nlp_processed_train.csv
  model_dir: artifacts/model_trainer/model/outputs
